# Generated by Django 2.2.7 on 2020-02-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Ques', models.CharField(max_length=320)),
                ('Op_1', models.CharField(max_length=100)),
                ('Op_2', models.CharField(max_length=100)),
                ('Op_3', models.CharField(max_length=100)),
                ('Op_4', models.CharField(max_length=100)),
                ('Ans', models.IntegerField()),
            ],
        ),
    ]
