# Generated by Django 2.2.7 on 2020-02-28 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDefinition',
            fields=[
                ('QuestionTypeId', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('QuestionType', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDefinition',
            fields=[
                ('SubjectId', models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=320, null=True)),
                ('Options', models.TextField(blank=True, null=True)),
                ('Ans', models.IntegerField()),
                ('QuestionTypeId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testsetup.QuestionDefinition')),
                ('SubjectId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testsetup.SubjectDefinition')),
            ],
        ),
    ]
