# Generated by Django 2.2.7 on 2020-02-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionTypeId', models.IntegerField(unique=True)),
                ('QuestionType', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(blank=True, max_length=100, null=True)),
                ('SubjectId', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Op_1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Op_2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Op_3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Op_4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Ques',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Subject',
        ),
        migrations.AddField(
            model_name='questions',
            name='Options',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='QuesType',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questions',
            name='Question',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='Subjectid',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
