# Generated by Django 2.2.7 on 2020-02-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsetup', '0002_auto_20200207_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondefinition',
            name='QuestionTypeId',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='SubjectId',
        ),
    ]
