# Generated by Django 2.2.7 on 2020-02-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsetup', '0003_auto_20200208_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='SubjectDefinition',
        ),
    ]
