# Generated by Django 2.2.7 on 2020-02-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsetup', '0004_auto_20200208_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Options',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
